### ISSUE TITLE
Doesn't work in Pre-Alpha 9 and Alpha

### ISSUE THREAD

**Issue by dredhorse** [robotman2000/Parkitect_BetterPerspectiveCamera#1]
Hi,

mod doesn't show up in the modlist and doesn't function.

Also R is already taken by the Coaster Cam, being able to configure keys would be cool.

Mac OSX 10.11.4

**Comment by dredhorse** [comment]
From the MOD log

16-05-03 09:48:00] Info: Source files: BetterPerspectiveCameraKeys.cs, BetterPerspectiveCameraMouse.cs, BetterPerspectiveCamera.cs, Main.cs from `/Users/mbreiden/Library/Application Support/Parkitect/pnmods/H-POPS@Parkitect_BetterPerspectiveCamera`.
[16-05-03 09:48:01] Error: CS0219: 165:19: The variable `num' is assigned but its value is never used in /Users/mbreiden/Library/Application Support/Parkitect/pnmods/H-POPS@Parkitect_BetterPerspectiveCamera/BetterPerspectiveCamera.cs
[16-05-03 09:48:01] Error: CS0649: 18:22: Field`BetterPerspective.BetterPerspectiveCameraMouse.PanSpeed' is never assigned to, and will always have its default value `0' in /Users/mbreiden/Library/Application Support/Parkitect/pnmods/H-POPS@Parkitect_BetterPerspectiveCamera/BetterPerspectiveCameraMouse.cs
[16-05-03 10:19:42] Info: Loaded build-160503094800615, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null.
[16-05-03 10:19:42] Fatal: Exception during loading: The classes in the module cannot be loaded..

**Comment by H-POPS** [comment]
Could try it again? I updated it, I fixed the things that showed up in the log.

**Comment by dredhorse** [comment]
The Error of the last line still exist, the modul can't be loaded.

**Comment by H-POPS** [comment]
Did it work with older versions of Parkitect?

**Comment by H-POPS** [comment]
And do you get this error when you are starting the game or when you installed/recompiled the mod?

**Comment by dredhorse** [comment]
pre-Alpha 9 was the first version, deleted the mod directory, removed all other mods, did download and start again... log at http://pastebin.com/g54fXU0Z

**Comment by H-POPS** [comment]
Can you also send the log file of the game, it's based in: ~/Library/Logs/Unity/Player.log

**Comment by dredhorse** [comment]
will do.. found this https://parkitectnexus.com/forum/2/Parkitect%20Nexus-website-client/268/osx-some-mods-wont-show-up-in-game

http://pastebin.com/PAByafBX Player Log

**Comment by H-POPS** [comment]
Hmmm, based on the forum I can't really do something about it at the moment.

**Comment by dredhorse** [comment]
question is what is the issue in mono / unity3d? I mean Perspective and the other camera mods work. So you need to do something different.

**Comment by dredhorse** [comment]
OK, one piece of code which creates the error is:
        public Func<float, float, float> GetTerrainHeight;
in BetterPerspectiveCamera

**Comment by dredhorse** [comment]
looking into the code that variable is useless (at least to my understand = null c# knowledge atm)

it is = null and will never be accessed anywhere else in your code.

**Comment by dredhorse** [comment]
I can confirm that remove that variable and the code with it will make the mod work again in OSX.

**Comment by H-POPS** [comment]
I changed it in the mod, can you try it now. How did you know this was the problem?

**Comment by MikeThinks** [comment]
I just accidentally updated the mod, and it no longer works, and does not show up in the mod list.  :(  Was working in A1 last night, tonight, clicked update in error and poof not working on PC version BTW

Thanks for your time :+1: 

[mod.txt](https://github.com/H-POPS/Parkitect_BetterPerspectiveCamera/files/249831/mod.txt)

**Comment by dredhorse** [comment]
Hi Mike :-)

see my Pull Request https://github.com/H-POPS/Parkitect_BetterPerspectiveCamera/pull/2

Hi H-Pops, I just recreated the mod bit by bit... that also pointed me to some issues people have with Func... I than checked if you needed it, and the code wasn't really used as GetTerrainHeight is declared null, never changed and the IF statement will only work with != null.

BTW: Any reason why you have the Gizmo stuff in the code?

**Comment by H-POPS** [comment]
I updated the mod with you request, it seems to work now. Could you also try it on OSX?

I actually made this for a game I was working on, that's why there are some debug features like Gizmos.

**Comment by dredhorse** [comment]
ahh. ok... will do today I guess... I'm off to play with the kids.

**Comment by MikeThinks** [comment]
Thanks!   I tried playing around with the CS file myself...but alas I know nothing of the syntax :(

Just copied over the BetterPerspectiveCamera.cs to a fresh install of the mod and it works now :)
